### ISSUE TITLE
Any tutorials on how to create one?

### ISSUE THREAD

**Issue by dgcnz** [laynH/Anime-Girls-Holding-Programming-Books#139]
I'm totally new to photo editing and I wanted to give GIMP a try. This was the "result":

![ced237b735f5fe74e0fd936bdd922a8d](https://user-images.githubusercontent.com/24966039/92985244-7e452380-f476-11ea-9849-7f96c7d6a1ce.jpg)

I couldn't find any tutorial for this, so do you have any tips? Feel free to close this issue if it's off-topic or something.

**Comment by Asday** [comment]
You wanna look up skewing and distortion.  Think about the transformation that happens to an image when you're looking at it from an angle, while it's bent.

**Comment by laynH** [comment]
tbh just familiarize youself with the tools in gimp. you can usually make a decent image with the basic tools in the Tools section on the left side of the screen

**Comment by laynH** [comment]
> tbh just familiarize youself with the tools in gimp. you can usually make a decent image with the basic tools in the Tools section on the left side of the screen

the Perspective is a pretty useful one for these images
