### ISSUE TITLE
why the fuck

### ISSUE THREAD

**Issue by videotoaster** [laynH/Anime-Girls-Holding-Programming-Books#204]
aren't the rust books the open-source version

**Comment by Asday** [comment]
Because you didn't make them with your choice of books?  Open a PR my dude.

**Comment by kotx** [comment]
It really doesn't matter IMO. You're not going to read the books in the image.

**Comment by Asday** [comment]
Why can't I react with :fire:?

**Comment by DanKGooGLy** [comment]
why the fuck

**Comment by videotoaster** [comment]
nevermind i'm just dumb
