### ISSUE TITLE
The Boys. Frenchie 

### ISSUE THREAD

**Issue by Greg0059** [laynH/Anime-Girls-Holding-Programming-Books#213]
In the Boys repo there's a addon called  Frenchie in there it has IPTV ALL . Live TV  the Hallmark Drama HD  Channel is not  been working for a few days  when you try to open  it  . It tries to open  but all you get is a message saying playback failed.  And there's a few others are the same  . Iam using the  Chains Repository  on kodi 19.1  matrix. Keep the good work up bringing hood addons.

**Comment by Asday** [comment]
What the hell did you just say.

**Comment by Greg0059** [comment]
Put another way  the live Channels  on are not working properly in the frenchie addon .  Like Hallmark Drama  Hallmark Channel HD  plus others.  On that addon.

**Comment by Asday** [comment]
This is a repository for sharing images of programming books being held by anime girls.  I have no idea what you're talking about, but this is not the place for it whatever it is.

**Comment by Greg0059** [comment]
OK I thought this was  the Boys  tv . My Bad.

**Comment by laynH** [comment]
tf?

**Comment by Asday** [comment]
I'm glad people that know more than me are similarly confused by this ticket.

I think it was a lost pirate or something.
