### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by chriskuech** [laynH/Anime-Girls-Holding-Programming-Books#64]
Please add a license so we can legally reference images without fear of copyright trolls

**Comment by boyEstrogen** [comment]
https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books/pull/65#issuecomment-499968351 

My reply on this pull requests summarises how I feel about adding a license. If something exists that meets the criteria Im open to adding it.

**Comment by shekeru** [comment]
While we're discussing a license again, I think we could benefit from pantsu.cat's [code of conduct](https://github.com/NyaaPantsu/nyaa/blob/dev/CODE_OF_CONDUCT.md)

**Comment by Asday** [comment]
I was all ready to come in "nah dude FUCK codes of conduct, contributions matter, not conduct herp derp derp" but then I read it.

10/10, :shipit:

**Comment by sharpaper** [comment]
Any update on this issue?

**Comment by Asday** [comment]
#wontfix

**Comment by ura-linux** [comment]
Can someone close this issue please

**Comment by Asday** [comment]
> If something exists that meets the criteria Im open to adding it.

It seems reasonable to keep the issue open if the search is still on.
