### ISSUE TITLE
Code in image is not C

### ISSUE THREAD

**Issue by Setok** [laynH/Anime-Girls-Holding-Programming-Books#97]
I believe this image is wrong:

C/Murakami_Shiina_Holding_Computer_C_Programming_Language.png

The code that is being shown does not appear to be C.

**Comment by Asday** [comment]
View the full image.

https://raw.githubusercontent.com/laynH/Anime-Girls-Holding-Programming-Books/master/C/Murakami_Shiina_Holding_Computer_C_Programming_Language.png

**Comment by Setok** [comment]
The book says C Language but the code on the laptop isn’t. Or is the intention to show that she is now learning some other language from what she was coding?

I’m confused.

**Comment by Asday** [comment]
The repository is called "Anime Girls Holding Programming **Books**" (emphasis mine).  The book matters.

Sent from Samsung Smart Fridge.

**Comment by Setok** [comment]
Yes, but as that picture is under the C directory and she is holding a C book, it makes one wonder why she is not coding C. 

Well, perhaps she is figuring out how to translate her code into C? That would of course be cause for celebration. But do we know that? Does that mean she’s not a C guru and thus not just using K&R to check the precedence rules? Or maybe she is coding something else but loves K&R so much she carries one around with her, whatever she might be working on (I do that too, so I could understand). 

This is a matter of grave importance. I need to know why her code is not C. I think I will have nightmares about this.

**Comment by Asday** [comment]
What if it is C, but you just don't recognise it because it's so good that you're blinded by it.  You're the people listening to the man speaking about the outside world in Plato's allegory of the cave.

**Comment by Setok** [comment]
This was indeed my first thought, especially as it’s unforgivably long since I last coded C. I started to question myself and wonder if maybe it might be C, but using constructs not familiar to myself or that I might, god forbid, have forgotten. I dug out my K&R to check and it indeed confirmed my suspicions that the code on her laptop is not C. Unless ... she is using some features of C so obscure that even Brian Kernighan and Dennis Ritchie felt better not to reveal to the world.

**Comment by laynH** [comment]
i dont give a shit

**Comment by procedural** [comment]
@laynH fuck you
