### ISSUE TITLE
Effective Java not included in compilation

### ISSUE THREAD

**Issue by mmacheerpuppy** [laynH/Anime-Girls-Holding-Programming-Books#98]
Effective Java is the absolute essential OOP programming reference.

Shame on you for not including this.

**Comment by windowsEmmie** [comment]
https://youtu.be/iYD5AG4RvHY?t=5 -> https://www.gimp.org/downloads/

**Comment by Asday** [comment]
Be the change that you want to see.

**Comment by mmacheerpuppy** [comment]
I am _not_ the hero of my own story.

**Comment by laynH** [comment]
> https://youtu.be/iYD5AG4RvHY?t=6 -> https://www.gimp.org/downloads/

do this
